In [1]:
import pandas as pd
import numpy as np

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 38.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

In [4]:
#en esta subieremos el raw
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline-2516232022/refs/heads/main/data/raw/F_envios.csv"

envios = pd.read_csv(url)

In [18]:
envios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 210 entries, 0 to 209
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_envio      210 non-null    object
 1   id_pedido     202 non-null    object
 2   direccion     210 non-null    object
 3   fecha_envio   200 non-null    object
 4   estado_envio  210 non-null    object
dtypes: object(5)
memory usage: 9.8+ KB

In [8]:
envios.isnull().sum()

id_envio         0
id_pedido        9
direccion        0
fecha_envio     10
estado_envio     0
dtype: int64

In [14]:
envios.duplicated().sum()

np.int64(0)

In [10]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [11]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

In [12]:
envios = normalizar_columnas(envios)
envios = limpiar_texto(envios)
envios = envios.drop_duplicates()

In [13]:
#Eliminar Duplicados
def eliminar_duplicados(df):
    return df.drop_duplicates()

In [24]:
envios["fecha_envio"] = pd.to_datetime(
    envios["fecha_envio"].astype(str).str.strip(),
    errors="coerce",
    dayfirst=True
)

In [25]:
envios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 210 entries, 0 to 209
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_envio      210 non-null    object
 1   id_pedido     202 non-null    object
 2   direccion     210 non-null    object
 3   fecha_envio   77 non-null     datetime64[ns]
 4   estado_envio  210 non-null    object
dtypes: datetime64[ns](1), object(4)
memory usage: 9.8+ KB

In [27]:
def validar_id(valor):
    import pandas as pd

    if pd.isna(valor):
        return False

    try:
        return int(valor) > 0
    except:
        return False

In [28]:
def validar_fila(row):
    errores = []

    # id_envio
    if not validar_id(row["id_envio"]):
        errores.append("id_envio_invalido")

    # id_pedido
    if not validar_id(row["id_pedido"]):
        errores.append("id_pedido_invalido")

    # direccion
    if pd.isna(row["direccion"]):
        errores.append("direccion_nula")

    # fecha
    if pd.isna(row["fecha_envio"]):
        errores.append("fecha_envio_invalida")

    # estado
    estados_validos = ["pendiente", "enviado", "entregado"]
    if row["estado_envio"] not in estados_validos:
        errores.append("estado_envio_invalido")

    return ", ".join(errores)

In [30]:
columnas_obligatorias = [
    "id_envio",
    "id_pedido",
    "direccion",
    "fecha_envio",
    "estado_envio"
]

validos = envios [
 envios[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = envios [
 envios[columnas_obligatorias].notna().all(axis=1)
].copy()

In [31]:
validos.to_csv("envios_curated.csv", index=False)
rechazados.to_csv("envios_rejects.csv", index=False)

In [32]:
validos.head()

,id_envio,id_pedido,direccion,fecha_envio,estado_envio
0,ENV8000,PED7100,"Boulevard Constitución, San Salvador",2024-02-06,en ruta
1,ENV8001,PED7222,"Calle El Mirador, La Libertad",2024-07-05,entregado
3,ENV8003,PED7186,"Av. Roosevelt, San Miguel",2024-03-07,en ruta
4,ENV8004,PED7043,"Calle Principal, San Salvador",2024-09-01,preparando
5,ENV8005,PED7008,"Pje. Las Flores, Sonsonate",2024-03-03,devuelto

In [33]:
validos.dtypes

id_envio                object
id_pedido               object
direccion               object
fecha_envio     datetime64[ns]
estado_envio            object
dtype: object

In [34]:
validos.isnull().sum()

id_envio        0
id_pedido       0
direccion       0
fecha_envio     0
estado_envio    0
dtype: int64

In [35]:
validos.value_counts()

id_envio  id_pedido  direccion                             fecha_envio  estado_envio
ENV8000   PED7100    Boulevard Constitución, San Salvador  2024-02-06   en ruta         1
ENV8001   PED7222     Calle El Mirador, La Libertad        2024-07-05   entregado       1
ENV8003   PED7186    Av. Roosevelt, San Miguel             2024-03-07   en ruta         1
ENV8004   PED7043    Calle Principal, San Salvador         2024-09-01   preparando      1
ENV8005   PED7008    Pje. Las Flores, Sonsonate            2024-03-03   devuelto        1
                                                                                       ..
ENV8201   PED7120    Pje. Las Flores, Santa Ana            2024-03-05   en ruta         1
ENV8202   PED7122    Calle Principal, Santa Ana            2024-10-09   devuelto        1
ENV8204   PED7147    Av. Roosevelt, Usulután               2024-09-02   entregado       1
ENV8206   PED7192    Av. Roosevelt, La Libertad            2025-06-05   preparando      1
ENV8209   PED7195    Av. Roosevelt, Sonsonate              2024-09-07   en ruta         1
Name: count, Length: 71, dtype: int64